In [18]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [19]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
a.shape

(2, 4)

In [21]:
a.shape = (4, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [22]:
a.shape = (2, -1)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
b = a.reshape(4, -1)
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
a[0][0] = 10

In [26]:
a

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [27]:
b

array([[10,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

In [28]:
a.dtype

dtype('int64')

In [29]:
np.typeDict

{0: numpy.bool_,
 1: numpy.int8,
 2: numpy.uint8,
 3: numpy.int16,
 4: numpy.uint16,
 5: numpy.int32,
 6: numpy.uint32,
 7: numpy.int64,
 8: numpy.uint64,
 9: numpy.int64,
 10: numpy.uint64,
 11: numpy.float32,
 12: numpy.float64,
 13: numpy.float128,
 14: numpy.complex64,
 15: numpy.complex128,
 16: numpy.complex256,
 17: numpy.object_,
 18: numpy.string_,
 19: numpy.unicode_,
 20: numpy.void,
 21: numpy.datetime64,
 22: numpy.timedelta64,
 23: numpy.float16,
 '?': numpy.bool_,
 'B': numpy.uint8,
 'Bool': numpy.bool_,
 'Complex128': numpy.complex256,
 'Complex32': numpy.complex64,
 'Complex64': numpy.complex128,
 'D': numpy.complex128,
 'Datetime64': numpy.datetime64,
 'F': numpy.complex64,
 'Float128': numpy.float128,
 'Float16': numpy.float16,
 'Float32': numpy.float32,
 'Float64': numpy.float64,
 'G': numpy.complex256,
 'H': numpy.uint16,
 'I': numpy.uint32,
 'Int16': numpy.int16,
 'Int32': numpy.int32,
 'Int64': numpy.int64,
 'Int8': numpy.int8,
 'L': numpy.uint64,
 'M': numpy.dat

In [30]:
set(np.typeDict.values())

{numpy.object_,
 numpy.bool_,
 numpy.string_,
 numpy.unicode_,
 numpy.void,
 numpy.int8,
 numpy.int16,
 numpy.int32,
 numpy.int64,
 numpy.int64,
 numpy.uint8,
 numpy.uint16,
 numpy.uint32,
 numpy.uint64,
 numpy.uint64,
 numpy.float16,
 numpy.float32,
 numpy.float64,
 numpy.float128,
 numpy.datetime64,
 numpy.timedelta64,
 numpy.complex64,
 numpy.complex128,
 numpy.complex256}

In [31]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [32]:
np.linspace(0, 1, 10)

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [36]:
np.linspace(0, 1, 10, endpoint=False)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [40]:
np.logspace(0, 2, 10)

array([   1.        ,    1.66810054,    2.7825594 ,    4.64158883,
          7.74263683,   12.91549665,   21.5443469 ,   35.93813664,
         59.94842503,  100.        ])

In [42]:
np.logspace(0, 3, 4, base=2)

array([ 1.,  2.,  4.,  8.])

In [44]:
np.empty((2, 3), np.int)

array([[             0,       46703336, 47803063322992],
       [46912674847416, 46912518563248, 46912518488232]])

In [45]:
np.zeros((2, 3), np.int)

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
np.ones((2, 3), np.int)

array([[1, 1, 1],
       [1, 1, 1]])

In [47]:
np.empty_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [48]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [49]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [52]:
s = "abcdef"
np.fromstring(s, dtype=np.int8)

array([ 97,  98,  99, 100, 101, 102], dtype=int8)

In [53]:
np.fromstring(s, dtype=np.int16)

array([25185, 25699, 26213], dtype=int16)

In [55]:
!echo $((98*256+97))

25185


In [59]:
a = np.arange(10)

In [60]:
a[0], a[5], a[9] #通过整数作为下标访问数组

(0, 5, 9)

In [61]:
a[0:5] #还可以是切片，切片的所有用法都可以用在这类

array([0, 1, 2, 3, 4])

In [62]:
a[5:-1]

array([5, 6, 7, 8])

In [64]:
a[1:-1:2]

array([1, 3, 5, 7])

In [69]:
a[::-1] #切片的开始下标和结束下标可以结束，步长-1表示整个数组头尾颠倒

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a[[0, 2, 4, 8]] #可以通过整数数组存取

array([0, 2, 4, 8])

In [67]:
a[[0, 2, 4, -1]] #整数数组中可以包含负数

array([0, 2, 4, 9])

In [73]:
b = a[0:2] #a和b共享内存
a[0] = 10
print "a={}".format(a)
print "b={}".format(b)

a=[10  1  2  3  4  5  6  7  8  9]
b=[10  1]


In [79]:
c = a[[0, 1, 2, 3]] #以整数数组方式访问，a和c不共享内存
c[0] = 0
print "a is {}".format(a)
print "c is {}".format(c)

a is [10  1  2  3  4  5  6  7  8  9]
c is [0 1 2 3]


In [86]:
b = a[np.array([[1,2,3], [4,5,6]])]
b

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
x = np.random.rand(5)
print "x: {}".format(x)

bool_array = x>0.5
print "bool array: {}".format(bool_array)

x[bool_array]

x: [ 0.61081095  0.20557952  0.60198909  0.79910561  0.48294425]
bool array: [ True False  True  True False]


array([ 0.61081095,  0.60198909,  0.79910561])

In [108]:
def func(i, j):
    return i*5 + j

a = np.fromfunction(func, (5, 5))
print "------------------ a ------------------"
print a

print "-------------- a[0, 3:5] --------------"
print a[0, 3:5]

print "-------------- a[3:, 3:] --------------"
print a[3:, 3:]

print "--------------- a[:, 3] ---------------"
print a[:, 3]

print "------------ a[2::2, ::2] -------------"
print a[2::2, ::2]

------------------ a ------------------
[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.]]
-------------- a[0, 3:5] --------------
[ 3.  4.]
-------------- a[3:, 3:] --------------
[[ 18.  19.]
 [ 23.  24.]]
--------------- a[:, 3] ---------------
[  3.   8.  13.  18.  23.]
------------ a[2::2, ::2] -------------
[[ 10.  12.  14.]
 [ 20.  22.  24.]]


In [111]:
b = a[:, 3] # a与b共享内存
b[0] = 10
print b
print a

[ 10.   8.  13.  18.  23.]
[[  0.   1.   2.  10.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.]]


##函数库
###求和

In [115]:
a = np.array([1, 2, 3, 4, 5])
sum = np.sum(a)
print "sum of a is {}".format(sum)

sum of a is 15


In [120]:
a = np.random.randint(0, 10, size=(4, 5))
a

[[0 9 6 9 8]
 [4 5 6 6 2]
 [9 0 7 7 9]
 [7 3 4 2 5]]
108


In [121]:
print np.sum(a) #当数组是多维时，计算所有元素之和

108


In [122]:
print np.sum(a, axis=0)

[20 17 23 24 24]


In [123]:
print np.sum(a, axis=1)

[32 23 32 21]


In [126]:
max = np.max(a)
print max

9


In [132]:
max_index = np.argmax(a)
print max_index

max_index = np.unravel_index(max_index, a.shape)
print max_index
print a[max_index]

1
(0, 1)
9


In [133]:
np.sort(a) #axis默认为1，对行排序

array([[0, 6, 8, 9, 9],
       [2, 4, 5, 6, 6],
       [0, 7, 7, 9, 9],
       [2, 3, 4, 5, 7]])

In [135]:
np.sort(a, axis=0)

array([[0, 0, 4, 2, 2],
       [4, 3, 6, 6, 5],
       [7, 5, 6, 7, 8],
       [9, 9, 7, 9, 9]])